modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="wildflowers"
version="0.2.2"
displayName="WildFlowers"
credits="N/A"
displayURL="https://modrinth.com/mod/wild-flowers"
logoFile="logo.png"
authors="Dynamo"
description="Flowers and plants for your enjoyment."

[[dependencies.wildflowers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




